project:
  type: website
  output-dir: _site

website:
  title: "Carlo Costantini"

  description: >-
    Evolutionary ecology, mosquito biology, and quantitative approaches to understanding organism–environment interactions.

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research/index.qmd
      - text: Publications
        href: publications/index.qmd

  search:
    location: navbar
    type: overlay

  back-to-top-navigation: true

  page-footer:
    left: "© 2026 Carlo Costantini"

    center:
      - text: "MIVEGEC"
        href: https://mivegec.fr/fr/annuaire/agent?id=273
      - text: "ORCID"
        href: https://orcid.org/0000-0003-1016-129X
      - icon: github
        href: https://github.com/costantinicarlo

    right: "Last edited: {{< meta date-modified >}}"

    border: true

format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    citations-hover: true
    footnotes-hover: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

lang: en-GB

bibliography: bibliography/references.bib
